easy_admin:
    site_name: 'Wild Circus'

    entities:
        Picture:
            class: App\Entity\Picture
        Category:
            class: App\Entity\Category
        User:
            class: App\Entity\User
        Show:
            class: App\Entity\Show
